### ISSUE TITLE
Intro to pandas - Division by zero

### ISSUE THREAD

**Issue by ChongHan** [ChongHan/adaepfl-Homework#1]
To avoid division by zero when applying a function. In the example, 

``` python
def slugging(x): 
    bases = x['h']-x['X2b']-x['X3b']-x['hr'] + 2*x['X2b'] + 3*x['X3b'] + 4*x['hr']
    ab = x['ab']+1e-6

    return bases/ab

baseball.apply(slugging, axis=1).round(3)
```

In our solution  @(RA-Danny): 

``` python
def odp(x):
    top = x['h'] + x['bb'] + x['hbp']
    bottom = x['ab'] + x['bb'] + x['hbp'] + x['sf']
    if bottom==0:
        return 0
    return top/bottom

baseball.apply(odp, axis=1).sort_values(ascending=False)
```

The example added **1e-6** to bottom ab to avoid division by zero, so the result of the function when divided by 0 will result in a very large number. whereas in our implementation it will be 0 (probably not desired output).

**Comment by RA-Danny** [comment]
So you think it will be better to set bottom to 1e-6 in that case ?'

**Comment by ChongHan** [comment]
Yep, I agree with the code used in the example. divide a very small number instead of returning any default value. Or if bottom == 0, then divide 1e-6

**Comment by RA-Danny** [comment]
Actually I disagree :) 
The problem is that we are computing the _on base **percentage**_. So it cannot be greater than 1, which may with a very small number as divider.

So for me, we keep it like that, with _return 0_
